sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: food_flasher
    username: root
    password: 123456
  upload:
    local: ../files/
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wx5121b83b00760e2c
    secret: 76855f250bffb5ba901b27753c4f7255